co_name = str(input())
co_adr = str(input())
co_tel = str(input())
co_fax = str(input())
co_web = str(input())
name_1 = str(input())
name_2 = str(input())
age = str(input())
tel_2 = str(input())

print(co_name)
print(f"Address: {co_adr}")
print(f"Tel. {co_tel}")
print(f"Fax: {co_fax}")
print(f"Web site: {co_web}")
print(f"Manager: {name_1} {name_2} (age: {age}, tel. {tel_2})")
